id: D22395F58
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T11:06:49+00:00'
last_modified: '2022-05-30T06:59:19.712745+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '1540':
      image_group_id: I1PD95891
      title: རྣལ་འབྱོར་ཡན་ལག་དྲུག་པ།
      total_pages: 1712
      order: 46
      base_file: 1540.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
