id: P61998818
initial_creation_type: ocr
source_metadata:
  volumes:
    16c63e2c9383477aa62b8c8a166a4082:
      base_file: v046.txt
      image_group_id: I1PD95891
      title: རྣལ་འབྱོར་ཡན་ལག་དྲུག་པ།
      total_pages: 1712
      volume_number: 46
